# Generated by Django 3.0.8 on 2021-07-12 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_representantes', '0001_initial'),
        ('gestion_profesionales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parentesco', models.CharField(max_length=12, verbose_name='parentesco')),
                ('grado', models.CharField(blank=True, choices=[('1', 'Grado1'), ('2', 'Grado2'), ('3', 'Grado3')], max_length=100, null=True)),
                ('rut', models.CharField(max_length=12, verbose_name='rut')),
                ('nombres', models.CharField(max_length=200, verbose_name='nombres')),
                ('apellidos', models.CharField(max_length=200, verbose_name='apellidos')),
                ('edad', models.IntegerField(verbose_name='edad')),
                ('sexo', models.CharField(blank=True, choices=[('1', 'Masculino'), ('2', 'Femenino')], max_length=100, null=True)),
                ('nacionalidad', models.CharField(max_length=50, verbose_name='nacionalidad')),
                ('ciudad_nacimiento', models.CharField(max_length=150, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('estado', models.CharField(blank=True, choices=[('1', 'Activo'), ('2', 'Inactivo')], max_length=100, null=True)),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_representantes.Representante')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, verbose_name='rut paciente')),
                ('nombres', models.CharField(max_length=200, verbose_name='nombre paciente')),
                ('apellidos', models.CharField(max_length=200, verbose_name='apellido paciente')),
                ('hora_atencion', models.TimeField(blank=True, null=True)),
                ('fecha_atencion', models.DateField(blank=True, null=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_profesionales.Profesionale')),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_representantes.Representante')),
            ],
            options={
                'verbose_name': 'Ficha',
                'verbose_name_plural': 'Fichas',
            },
        ),
    ]
