# Generated by Django 3.0.8 on 2021-07-12 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_profesionales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(verbose_name='Fecha de reserva')),
                ('hora_reserva', models.TimeField(verbose_name='Hora de reserva')),
                ('estado', models.CharField(choices=[('0', 'Libre'), ('1', 'Ocupada')], default='0', max_length=1, verbose_name='Estado reserva')),
                ('especialidad', models.CharField(choices=[('Fonoaudilogo', 'Fonoaudilogo'), ('Terapeuta Ocupacional', 'Terapeuta'), ('Psicologo', 'Psicologo')], default=None, max_length=100)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_profesionales.Profesionale')),
            ],
        ),
    ]
