# Generated by Django 3.0.8 on 2021-07-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('representante', models.CharField(max_length=200, verbose_name='nombre representante')),
                ('correo', models.EmailField(max_length=150)),
                ('contacto', models.CharField(max_length=12, verbose_name='contacto')),
                ('paciente', models.CharField(max_length=200, verbose_name='nombre paciente')),
                ('especialista', models.CharField(max_length=200, verbose_name='nombre especialista')),
                ('especialidad', models.CharField(blank=True, max_length=200, null=True, verbose_name='Especialidad')),
                ('hora_atencion', models.TimeField(blank=True, null=True)),
                ('fecha_atencion', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
